name: Publish Mobile Android - Release

on:
  workflow_dispatch:
    inputs:
      releaseNotes:
        description: 'Changes on this build: '
        required: true
        default: 'No relevant changes.'
        type: string
  push:
    branches:
      - 'release'
    paths:
      - 'apps/bierdeliveryapp/**/*'
      - 'libs/bierdeliveryapp/**/*'

env:
  NX_RN_APP_PATH: ${{ 'apps/bierdeliveryapp' }}
  NX_RN_APP_NAME: ${{ 'bierdeliveryapp' }}
  ANDROID_VARIANT: ${{ '' }}
  ANDROID_VARIANT_RELEASE_PATH: ${{ '/android/app/build/outputs/apk/release' }}
  ANDROID_APK_FILENAME: ${{ 'app-release.apk' }}

jobs:
  android-build:
    name: Android Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - uses: actions/checkout@v2
      - name: Build Android Composite
        uses: daviaugustos/Nrwl-Nx-Android-Build-Action@v5
        with:
          app-path: ${{ env.NX_RN_APP_PATH }}
          nx-app-name: ${{ env.NX_RN_APP_NAME }}
          signing-key: ${{ secrets.BIER_DELIVERY_APP_ANDROID_SIGNING_KEY }}
          keystore-alias: ${{ secrets.BIER_DELIVERY_APP_ANDROID_ALIAS }}
          keystore-password: ${{ secrets.BIER_DELIVERY_APP_ANDROID_KEY_STORE_PASSWORD }}
          key-password: ${{ secrets.BIER_DELIVERY_APP_ANDROID_KEY_PASSWORD }}
          variant-flavor: ${{ env.ANDROID_VARIANT }}
          variant-flavor-apk-path:  ${{ env.ANDROID_VARIANT_RELEASE_PATH }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ANDROID_APK_FILENAME }}
          path: ${{ env.NX_RN_APP_PATH }}${{ env.ANDROID_VARIANT_RELEASE_PATH }}

  deploy:
    needs: [android-build]
    if: success()
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v3
        with:
          name: ${{ env.ANDROID_APK_FILENAME }}

      - name: Set up our JDK environment
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11

      - name: Upload artifact to App Center
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: Midnight-Front/Bier-Delivery-Android
          token: ${{secrets.BIER_DELIVERY_APP_APPCENTER_TOKEN_ANDROID}}
          group: Collaborators
          file: ${{ env.ANDROID_APK_FILENAME }}
          notifyTesters: true
          debug: false
          releaseNotes: ${{ github.event.inputs.releaseNotes }}

      - name: Delete Artifact
        uses: geekyeggo/delete-artifact@v1
        with:
          name: ${{ env.ANDROID_APK_FILENAME }}